#!/usr/bin/env bash
# Rebuild the question bank index from all question YAML files.
# Called by the auto-rebuild-question-index hook after questions are modified.
#
# Scans all .yaml files in the questions/ directory (except _index.yaml),
# counts questions per category, and rebuilds _index.yaml.

set -euo pipefail

# Read hook input from stdin
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# Only rebuild index for writes to */questions/*.yaml
if [[ -z "$FILE_PATH" || ! "$FILE_PATH" =~ /questions/[^/]*\.yaml$ ]]; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUESTIONS_DIR="$(cd "$SCRIPT_DIR/../questions" && pwd)"
INDEX_FILE="$QUESTIONS_DIR/_index.yaml"

if [[ ! -d "$QUESTIONS_DIR" ]]; then
  echo "Questions directory not found at $QUESTIONS_DIR" >&2
  exit 0
fi

TOTAL=0
CATEGORIES=""
SKILLS_MAP=""
LEVELS_MAP=""
STAGES_MAP=""

for qfile in "$QUESTIONS_DIR"/*.yaml; do
  [[ -f "$qfile" ]] || continue
  filename=$(basename "$qfile")

  # Skip the index itself and custom overrides
  [[ "$filename" == "_index.yaml" ]] && continue

  category="${filename%.yaml}"

  # Count questions (lines starting with "  - id:")
  count=$(grep -c "^  - id:" "$qfile" 2>/dev/null || echo "0")
  TOTAL=$((TOTAL + count))

  # Collect subcategories
  subcategories=$(grep "^    subcategory:" "$qfile" 2>/dev/null | sed 's/.*: *//' | sort -u | tr '\n' ',' | sed 's/,$//')

  # Collect question IDs
  ids=$(grep "^  - id:" "$qfile" 2>/dev/null | sed 's/.*: *//' | tr '\n' ' ')

  CATEGORIES="${CATEGORIES}  ${category}:\n    file: ${filename}\n    count: ${count}\n    subcategories: [${subcategories}]\n"

  # Build skills map entries
  for id in $ids; do
    # Extract skills_tested for this question (simplified — gets the line after id match)
    skills_line=$(awk "/^  - id: ${id}$/,/^  - id:/" "$qfile" | grep "skills_tested:" | head -1 | sed 's/.*\[//;s/\]//')
    if [[ -n "$skills_line" ]]; then
      IFS=',' read -ra skills <<< "$skills_line"
      for skill in "${skills[@]}"; do
        skill=$(echo "$skill" | tr -d ' ')
        [[ -z "$skill" ]] && continue
        SKILLS_MAP="${SKILLS_MAP}    ${skill}: [${id}]\n"
      done
    fi

    # Build levels map entries
    levels_line=$(awk "/^  - id: ${id}$/,/^  - id:/" "$qfile" | grep "    level:" | head -1 | sed 's/.*\[//;s/\]//')
    if [[ -n "$levels_line" ]]; then
      IFS=',' read -ra levels <<< "$levels_line"
      for level in "${levels[@]}"; do
        level=$(echo "$level" | tr -d ' ')
        [[ -z "$level" ]] && continue
        LEVELS_MAP="${LEVELS_MAP}    ${level}: [${id}]\n"
      done
    fi

    # Build stages map entries
    stages_line=$(awk "/^  - id: ${id}$/,/^  - id:/" "$qfile" | grep "    stages:" | head -1 | sed 's/.*\[//;s/\]//')
    if [[ -n "$stages_line" ]]; then
      IFS=',' read -ra stages <<< "$stages_line"
      for stage in "${stages[@]}"; do
        stage=$(echo "$stage" | tr -d ' ')
        [[ -z "$stage" ]] && continue
        STAGES_MAP="${STAGES_MAP}    ${stage}: [${id}]\n"
      done
    fi
  done
done

# Write index
cat > "$INDEX_FILE" << INDEXEOF
# Question bank index
# Auto-generated by rebuild-question-index.sh — do not edit manually

generated: $(date +%Y-%m-%d)
total_questions: $TOTAL

categories:
$(echo -e "$CATEGORIES")
skills_map:
$(echo -e "$SKILLS_MAP" | sort -t: -k1 | uniq)

levels_map:
$(echo -e "$LEVELS_MAP" | sort -t: -k1 | uniq)

stages_map:
$(echo -e "$STAGES_MAP" | sort -t: -k1 | uniq)
INDEXEOF

echo "Question index rebuilt: $TOTAL questions"
